In [5]:
from qutip import *
import numpy as np
from numpy.linalg import eig
import math

sig_1 = ""
sig_2 = ""
sig_3 = ""
sig_4 = ""
sig_1 = input("Signo (+ ó -) para |00>: ")
sig_1 = sig_1 + "1"
sig_2 = input("Signo (+ ó -) para |01>: ")
sig_2 = sig_2 + "1"
sig_3 = input("Signo (+ ó -) para |10>: ")
sig_3 = sig_3 + "1"
sig_4 = input("Signo (+ ó -) para |11>: ")
sig_4 = sig_4 + "1"

ket_1 = 0
ket_2 = 0
ket_3 = 0
ket_4 = 0
ket_1 = int(sig_1) #Se hará un casteo para almacenar el número 1 con el signo (+ o -) dado por el usuario.
ket_2 = int(sig_2)
ket_3 = int(sig_3)
ket_4 = int(sig_4)

state = Qobj([[ket_1,ket_2,ket_3,ket_4]],dims=[[2, 2], [2, 2]]) #Se creara el estado.
state = state.dag()
state = state.unit() #Para apegarnos al ejemplo del libro, se aplica la función unit para normalizar el estado.
print("\nEstado\n",state)

state_density = state * state.dag()
print("\nMatriz del operador de densidad\n",state_density)

state_partial_transpose = partial_transpose(state_density, [0,1])
print("\nMatriz de la transposicion parcial\n",state_partial_transpose)

state_arr = np.stack(state_partial_transpose).astype(None)
state_arr

state_arr_conv = state_arr.reshape(4,2*2)

state_around = np.around(state_arr_conv,decimals=2)

w,v=eig(state_around)
print('\nEigenvalores:', w)

count = 0
for x in w:
    if x >= 0:
        count+=1
if count == len(w):
    print("\nAplicando la condición de transposición parcial de Peres, los eigenvalores son mayores o iguales a 0,\nentonces es un estado separable.")
else:
    print("\nAplicando la condición de transposición parcial de Peres, hay algún eigenvalor negativo,\nentonces es un estado entrelazado (entangled)")

Signo (+ ó -) para |00>: +
Signo (+ ó -) para |01>: -
Signo (+ ó -) para |10>: -
Signo (+ ó -) para |11>: +

Estado
 Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 1), type = oper, isherm = False
Qobj data =
[[ 0.49999999]
 [-0.49999999]
 [-0.49999999]
 [ 0.49999999]]

Matriz del operador de densidad
 Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.24999999 -0.24999999 -0.24999999  0.24999999]
 [-0.24999999  0.24999999  0.24999999 -0.24999999]
 [-0.24999999  0.24999999  0.24999999 -0.24999999]
 [ 0.24999999 -0.24999999 -0.24999999  0.24999999]]

Matriz de la transposicion parcial
 Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.24999999 -0.24999999 -0.24999999  0.24999999]
 [-0.24999999  0.24999999  0.24999999 -0.24999999]
 [-0.24999999  0.24999999  0.24999999 -0.24999999]
 [ 0.24999999 -0.24999999 -0.24999999  0.24999999]]

Eigenvalores: [0. 1. 0. 0.]

Aplicando la condición

<ipython-input-5-b84aea84b3d3>:39: ComplexWarning: Casting complex values to real discards the imaginary part
  state_arr = np.stack(state_partial_transpose).astype(None)
